name: CI

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install mise
        uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: setup
        run: mise run setup

      - name: lint
        run: mise run lint
