name: Lint

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install mise
        uses: jdxcode/mise-action@v2

      - name: lint
        run: mise run lint
